[config]
skip_core_tasks = true

[tasks.default]
run_task = "copy-files"

[tasks.build-members]
run_task = { name = "build", fork = true }

[tasks.copy-files]
dependencies = ["build-members"]
workspace = false
script = '''
#!@duckscript
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
cp ./ferrous-kernel/target/x86_64-unknown-fe/debug/ferrous-kernel ./output/ferrous-kernel
cp ./oxidize/target/x86_64-unknown-uefi/debug/oxidize.efi ./output/oxidize.efi
cp ./oxidize/startup.nsh ./output/startup.nsh
'''

[tasks.run]
dependencies = ["copy-files"]
workspace = false
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
command = "qemu-system-x86_64"
args = ["-bios", "./OVMF.fd", "-net", "none", "-drive", "format=raw,file=fat:rw:./output/", "-device", "VGA"]

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
  "ferrous-kernel",
  "oxidize",
]