[build]
target = "x86_64-unknown-fe.json"

[target.x86_64-unknown-fe]
rustflags = ["-C", "link-arg=-Tkernel.ld"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
